#ifndef UI_UX_KONSOL_RANKING_H
#define UI_UX_KONSOL_RANKING_H


void TAMPILKAN_MENU_UTAMA();
void TAMPILKAN_MENU_MANAJEMEN_BUKU();
void TAMPILKAN_MENU_MANAJEMEN_ANGGOTA();
void TAMPILKAN_MENU_TRANSAKSI();


void TAMPILKAN_SEMUA_BUKU();
void TAMPILKAN_SEMUA_ANGGOTA();
void TAMPILKAN_RIWAYAT_PEMINJAMAN_ANGGOTA();


void TAMPILKAN_RANKING_BUKU();
void ATUR_PENGATURAN_SISTEM();

#endif 